# FastAPI utilities 
from fastapi import APIRouter, Depends, HTTPException, status, Response, Cookie

# SQLAlchemy database session
from sqlalchemy.orm import Session

from app.models.refresh_token import RefreshToken

from datetime import datetime, timezone

from fastapi import Cookie, Response

# Database dependency
from app.database import get_db

# SQLAlchemy User database model
from app.models.user import User

# Pydantic request/response schemas
from app.schemas.auth import (
    UserCreate,
    UserResponse,
    UserLogin,
)

# Authentication/security utilities
from app.core.security import (
    hash_password,
    verify_password,
    create_access_token,
    get_current_user,
    get_refresh_token_expiry,
    create_refresh_token,
    hash_refresh_token,
    is_access_token_valid,
    get_valid_refresh_token
)



"""
    Create a router for authentication-related endpoints.

    prefix="/auth" means every endpoint in this router
    will start with /auth.

    For example:
      @router.post("/login")
    becomes:
      POST /auth/login

    tags are used to group these endpoints in the
    automatically generated Swagger documentation.
"""
router = APIRouter(
    prefix="/auth",
    tags=["Authentication"],
)


# ---------------------------------------------------------
# SIGNUP
# ---------------------------------------------------------

@router.post(
    "/signup",
    response_model=UserResponse,
    status_code=status.HTTP_201_CREATED,
)
def signup(
    # FastAPI reads the request body and validates it
    # using the UserCreate Pydantic schema.
    user_data: UserCreate,

    # FastAPI automatically provides a database session
    # using our get_db dependency.
    db: Session = Depends(get_db),
):
    # Check whether a user with this email already exists.
    existing_user = (
        db.query(User)
        .filter(User.email == user_data.email)
        .first()
    )

    # If the email is already registered, stop the request
    # and return HTTP 400 Bad Request.
    if existing_user:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Email already registered",
        )

    # NEVER store the user's plain-text password.
    #
    # Convert the password into a secure password hash
    # before storing it in the database.
    hashed_password = hash_password(user_data.password)

    # Create a new SQLAlchemy User object.
    user = User(
        email=user_data.email,
        name=user_data.name,
        password_hash=hashed_password,
    )

    # Add the new user to the current database session.
    db.add(user)

    # Commit the transaction so the user is actually
    # written to the database.
    db.commit()

    # Refresh the object so SQLAlchemy loads values
    # generated by the database, such as the user ID.
    db.refresh(user)

    # Return the newly created user.
    #
    # FastAPI will format the response according to
    # the UserResponse schema.
    return user


# ---------------------------------------------------------
# LOGIN
# ---------------------------------------------------------

@router.post("/login")
def login(
    # Request body validated using the UserLogin schema.
    user_data: UserLogin,
    response: Response,
    # Get a database session through dependency injection.
    db: Session = Depends(get_db),
    access_token: str | None = Cookie(default=None),
    refresh_token: str | None = Cookie(default=None),
):
    # Already logged in with a valid access token
    if access_token and is_access_token_valid(access_token, db):
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="Already authenticated. Logout before logging in again.",
        )

    # Access token may be expired, but refresh token can still be valid
    if refresh_token:
        existing_session = get_valid_refresh_token(
            refresh_token,
            db,
        )

        if existing_session:
            raise HTTPException(
                status_code=status.HTTP_409_CONFLICT,
                detail="Already authenticated. Logout before logging in again.",
            )

    # Normal login from here
    # Find the user whose email matches the submitted email.
    user = (
        db.query(User)
        .filter(User.email == user_data.email)
        .first()
    )

    # If no user exists with that email,
    # authentication fails.
    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    # Compare the plain-text password supplied by the user
    # with the password hash stored in the database.
    if not verify_password(
        user_data.password,
        user.password_hash,
    ):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    # The credentials are valid.
    #
    # Create an access token containing information that
    # identifies the authenticated user.
    access_token = create_access_token(user.id)

    # Create long-lived refresh token
    refresh_token = create_refresh_token()

    # Store only the hash in the database
    refresh_token_record = RefreshToken(
        user_id=user.id,
        token_hash=hash_refresh_token(refresh_token),
        expires_at=get_refresh_token_expiry(),
    )

    db.add(refresh_token_record)
    db.commit()

    # Store access token in an HttpOnly cookie
    response.set_cookie(
        key="access_token",
        value=access_token,
        httponly=True,
        secure=True,
        samesite="lax",
        max_age=15 * 60,
    )

    # Store refresh token in an HttpOnly cookie
    response.set_cookie(
        key="refresh_token",
        value=refresh_token,
        httponly=True,
        secure=False, # wont work locally over http
        samesite="lax",
        max_age=7 * 24 * 60 * 60,
    )

    return {
        "message": "Login successful",
        "token": access_token,
    }


# refresh endpoint
@router.post("/refresh")
def refresh_access_token(
    response: Response,
    refresh_token: str | None = Cookie(default=None),
    db: Session = Depends(get_db),
):
    if refresh_token is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh token missing",
        )

    token_hash = hash_refresh_token(refresh_token)

    token_record = (
        db.query(RefreshToken)
        .filter(RefreshToken.token_hash == token_hash)
        .first()
    )

    if token_record is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid refresh token",
        )

    # Check whether the token was revoked
    if token_record.revoked_at is not None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh token has been revoked",
        )

    expires_at = token_record.expires_at

    if expires_at.tzinfo is None:
        expires_at = expires_at.replace(tzinfo=timezone.utc)

    if expires_at <= datetime.now(timezone.utc):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Refresh token has expired",
        )

    # Revoke the old refresh token
    token_record.revoked_at = datetime.now(timezone.utc)

    # Create a NEW refresh token
    new_refresh_token = create_refresh_token()

    new_refresh_token_record = RefreshToken(
        user_id=token_record.user_id,
        token_hash=hash_refresh_token(new_refresh_token),
        expires_at=get_refresh_token_expiry(),
    )

    db.add(new_refresh_token_record)

    # Create a fresh access JWT
    access_token = create_access_token(
        token_record.user_id
    )

    db.commit()

    response.set_cookie(
        key="access_token",
        value=access_token,
        httponly=True,
        secure=False,
        samesite="lax",
        max_age=15 * 60,
    )

    # Replace refresh-token cookie
    response.set_cookie(
        key="refresh_token",
        value=new_refresh_token,
        httponly=True,
        secure=False,
        samesite="lax",
        max_age=7 * 24 * 60 * 60,
    )

    return {
        "message": "Access token refreshed",
        "token": access_token,
    }



# logout endpoint
@router.post("/logout")
def logout(
    response: Response,
    refresh_token: str | None = Cookie(default=None),
    db: Session = Depends(get_db),
):
    if refresh_token is not None:
        token_hash = hash_refresh_token(refresh_token)

        token_record = (
            db.query(RefreshToken)
            .filter(RefreshToken.token_hash == token_hash)
            .first()
        )

        if token_record is not None:
            token_record.revoked_at = datetime.now(timezone.utc)
            db.commit()

    response.delete_cookie(
        key="access_token",
    )

    response.delete_cookie(
        key="refresh_token",
    )

    return {
        "message": "Logout successful",
    }
